In [1]:
import numpy as np

In [ ]:
# как создать матрицу?

In [2]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [26]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


/tmp/ipykernel_54659/1644361611.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [33]:
df[0][0]

ValueError: setting an array element with a sequence.

In [4]:
# размер матрицы
np.shape(A)

(4, 3)

In [5]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [6]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [7]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [8]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [ ]:
# создание специальных матриц

In [9]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [15]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [16]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [17]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [18]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [19]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [21]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [22]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [23]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [24]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [28]:
x_col.T

array([[1, 2, 3]])

In [26]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [5]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Составьте матрицу  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [17]:
Inc = np.array([Husband_Income.reshape(1,3), Wife_Income.reshape(1,3), Mother_In_Law_Income.reshape(1,3)]).T
Inc

array([[[100, 150,  90]],

       [[220, 200,  80]],

       [[140, 130, 100]]])

Составьте матрицу  расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.



In [20]:
Cons = np.array([Husband_Consumption.reshape(1,3), Wife_Consumption.reshape(1,3), Mother_In_Law_Consumption.reshape(1,3)]).T
Cons

array([[[ 50, 100, 100]],

       [[ 50,  80,  20]],

       [[ 60, 140, 140]]])

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу , где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [23]:
Inc * 0.87

array([[[ 87. , 130.5,  78.3]],

       [[191.4, 174. ,  69.6]],

       [[121.8, 113.1,  87. ]]])

Вычислите матрицу , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

Выберите список элементов из третьей строки этой матрицы:

In [24]:
Inc * 0.87 - Cons

array([[[ 37. ,  30.5, -21.7]],

       [[141.4,  94. ,  49.6]],

       [[ 61.8, -26.9, -53. ]]])