# Содержание

1. [Операции с матрицами](#matrices-operations)
    1. [Сложение и вычитание матриц](#adding-and-subtracting-matrices)
    2. [Сложение матриц](#matrices-add)
    3. [Вычитание матриц](#matrices-subtract)
    4. [Умножение матрицы на константу](#matrix-constant-multiplication)
    5. [Умножение матрицы на матрицу](#matrix-matrix-multiplication)
    6. [Транспонирование матрицы](#matrix-transpose)
    7. [Использование единичной и обратной матриц](#unit-and-inverse-matrices)
    8. [Ранг матрицы](#matrix-rank)
    9. [Определитель матрицы](#matrix-determinant)

# Операции с матрицами  <a class="anchor" id="matrices-operations"></a>

Python предоставляет несколько библиотек для работы с матрицами и выполнения операций над ними, таких как NumPy, SciPy, SymPy и др. Для начала импортируем необходимые библиотеки:

In [1]:
import numpy as np
import sympy as sp

##  Сложение и вычитание матриц  <a class="anchor" id="adding-and-subtracting-matrices"></a>

Матрицы могут быть сложены или вычитаны путем поэлементного сложения соответствующих элементов двух матриц одинакового размера. Эта операция доступна во всех библиотеках, которые поддерживают работу с матрицами.

## Сложение матриц <a class="anchor" id="matrices-add"></a>

### Numpy

Сложение матриц в NumPy можно выполнить с помощью оператора + или функции numpy.add(). Обе операции складывают соответствующие элементы двух матриц, которые должны быть одинакового размера.

Вот пример сложения двух матриц с помощью библиотеки NumPy:

In [2]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Сложение двух матриц
C = A + B
D = np.add(A, B)

# Вывод результата
print("Результат сложения двух матриц:")
print(C)
print(D)

Результат сложения двух матриц:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


Как видно, элементы матрицы C и матрицы D равны, так как эти две операции эквивалентны.

### Sympy

Сложение матриц в SymPy можно выполнить с помощью метода __add__() класса Matrix. Этот метод складывает соответствующие элементы двух матриц, которые должны быть одинакового размера.

Вот пример сложения двух матриц с помощью библиотеки SymPy:

In [3]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Сложение двух матриц
C = A + B

# Вывод результата
print("Результат сложения двух матриц:")
print(C)

Результат сложения двух матриц:
Matrix([[6, 8], [10, 12]])


Как видно, операция сложения двух матриц в SymPy производится очень просто и удобно, используя функцию sympy.Matrix().

## Вычитание матриц <a class="anchor" id="matrices-subtract"></a>

### Numpy

Для выполнения операции вычитания матриц с помощью NumPy, сначала мы создаем две матрицы A и B, используя функцию array и передавая ей списки значений для каждой строки матрицы. Затем мы используем оператор - для выполнения вычитания матриц A и B и сохраняем результат в новую матрицу C.

В данном примере C[i][j] будет содержать разность элементов на позиции (i, j) в матрицах A и B. Если элементы в матрицах A и B на соответствующих позициях равны, то соответствующий элемент в матрице C будет равен нулю.

In [4]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Вычитание матриц
C = A - B

# Вывод результата
print(C)

[[-4 -4]
 [-4 -4]]


Результатом будет новая матрица C, которая будет содержать разности элементов соответствующих позиций в матрицах A и B. Например, первый элемент C[0][0] будет равен A[0][0] - B[0][0], то есть 1 - 5 = -4.

### SymPy

Для выполнения операции вычитания матриц с помощью SymPy, мы создаем две матрицы A и B, используя класс Matrix и передавая ему списки значений для каждой строки матрицы. Затем мы используем метод __sub__ для выполнения вычитания матриц A и B и сохраняем результат в новую матрицу C.

В данном примере C[i, j] будет содержать разность элементов на позиции (i, j) в матрицах A и B. Отличие от NumPy заключается в том, что SymPy работает с символьными выражениями, а не с числами, поэтому C[i, j] будет содержать символьное выражение, представляющее разность элементов матриц A и B на соответствующих позициях.

После выполнения операции вычитания, мы можем вывести результат, используя просто вызов объекта C, который автоматически вызовет метод __repr__, показывающий результат в красиво отформатированном виде.

In [5]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Вычитание матриц
C = A - B

# Вывод результата
C

Matrix([
[-4, -4],
[-4, -4]])

Результатом будет новая матрица C, которая будет содержать разности элементов соответствующих позиций в матрицах A и B. Например, первый элемент C[0,0] будет равен A[0,0] - B[0,0], то есть 1 - 5 = -4.

Обратите внимание, что при использовании SymPy, матрицы представлены как объекты класса Matrix, а не ndarray, как в NumPy. Кроме того, операции с матрицами в SymPy выполняются с использованием символьных выражений, что позволяет работать с матрицами, содержащими переменные.

## Умножение матрицы на константу <a class="anchor" id="matrix-constant-multiplication"></a>

### Numpy

Умножение матрицы на константу в NumPy можно выполнить с помощью оператора * или функции numpy.multiply(). Оба метода умножают каждый элемент матрицы на заданную константу. Пример:

In [6]:
# Создание матрицы
A = np.array([[1, 2], [3, 4]])

# Умножение матрицы на константу
k = 2
B = k * A
C = np.multiply(k, A)

# Вывод результата
print("Результат умножения матрицы на константу:")
print(B)
print(C)

Результат умножения матрицы на константу:
[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


Как видно, элементы матрицы B и матрицы C равны, так как эти два метода эквивалентны.

### Sympy

Умножение матрицы на константу в SymPy можно выполнить с помощью метода multiply() объекта sympy.Matrix. Этот метод умножает каждый элемент матрицы на заданную константу. Пример:

In [7]:
# Создание матрицы
A = sp.Matrix([[1, 2], [3, 4]])

# Умножение матрицы на константу
k = 2
B = A.multiply(k)

# Вывод результата
print("Результат умножения матрицы на константу:")
print(B)

Результат умножения матрицы на константу:
Matrix([[2, 4], [6, 8]])


Как видно, элементы матрицы B равны умножению элементов матрицы A на константу k, что демонстрирует простоту и удобство работы с матрицами в SymPy.

## Умножение матрицы на матрицу <a class="anchor" id="matrix-matrix-multiplication"></a>

### Numpy

Умножение матрицы на матрицу в NumPy можно выполнить с помощью функции numpy.dot() или оператора @. Оба метода производят матричное умножение матрицы на матрицу, то есть каждый элемент новой матрицы получается как сумма произведений элементов строки первой матрицы на элементы столбца второй матрицы. Пример умножения матрицы на матрицу с помощью библиотеки NumPy:

In [8]:
# Создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Умножение матриц
C = np.dot(A, B)
D = A @ B

# Вывод результата
print("Результат умножения матриц:")
print(C)
print(D)

Результат умножения матриц:
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Как видно, результаты выполнения методов numpy.dot() и @ совпадают и равны матрице, полученной в результате умножения матрицы A на матрицу B.

### Sympy

Умножение матрицы на матрицу в SymPy можно выполнить с помощью метода sympy.Matrix() и оператора *. Метод sympy.Matrix() используется для представления матриц и векторов как объектов SymPy, а оператор * выполняет матричное умножение двух матриц.

Пример умножения матрицы на матрицу с помощью библиотеки SymPy:

In [9]:
# Создание двух матриц
A = sp.Matrix([[1, 2], [3, 4]])
B = sp.Matrix([[5, 6], [7, 8]])

# Умножение матриц
C = A * B

# Вывод результата
print("Результат умножения матриц:")
print(C)

Результат умножения матриц:
Matrix([[19, 22], [43, 50]])


Как видно, результатом выполнения операции A * B является матрица, полученная в результате умножения матрицы A на матрицу B.

## Транспонирование матрицы <a class="anchor" id="matrix-transpose"></a>

### Numpy

Транспонирование матрицы в NumPy можно выполнить с помощью метода numpy.transpose() или атрибута T. Оба метода возвращают новую матрицу, которая получается из исходной матрицы путем замены строк на столбцы (и наоборот). Пример транспонирования матрицы с помощью библиотеки NumPy:

In [10]:
# Создание матрицы
A = np.array([[1, 2], [3, 4], [5, 6]])

# Транспонирование матрицы
B = np.transpose(A)
C = A.T

# Вывод результата
print("Исходная матрица:")
print(A)
print("Транспонированная матрица:")
print(B)
print(C)

Исходная матрица:
[[1 2]
 [3 4]
 [5 6]]
Транспонированная матрица:
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


Как видно, результаты выполнения методов numpy.transpose() и T совпадают и равны транспонированной матрице, полученной из исходной матрицы A.

### Sympy

Транспонирование матрицы в SymPy можно выполнить с помощью метода transpose() или атрибута T. Оба метода возвращают новую матрицу, которая получается из исходной матрицы путем замены строк на столбцы (и наоборот). Пример транспонирования матрицы с помощью библиотеки SymPy:

In [11]:
# Создание матрицы
A = sp.Matrix([[1, 2], [3, 4], [5, 6]])

# Транспонирование матрицы
B = A.transpose()
C = A.T

# Вывод результата
print("Исходная матрица:")
print(A)
print("Транспонированная матрица:")
print(B)
print(C)

Исходная матрица:
Matrix([[1, 2], [3, 4], [5, 6]])
Транспонированная матрица:
Matrix([[1, 3, 5], [2, 4, 6]])
Matrix([[1, 3, 5], [2, 4, 6]])


Как видно, результаты выполнения методов sympy.Matrix.transpose() и T совпадают и равны транспонированной матрице, полученной из исходной матрицы A.

## Использование единичной и обратной матриц <a class="anchor" id="unit-and-inverse-matrices"></a>

### Numpy

В библиотеке NumPy есть функции для создания единичной и обратной матриц.

Единичная матрица - это квадратная матрица, у которой все элементы главной диагонали равны 1, а остальные элементы равны 0. Единичную матрицу в NumPy можно создать с помощью функции eye. Например, чтобы создать 3x3 единичную матрицу, нужно использовать следующий код:

In [12]:
import numpy as np

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Обратная матрица - это квадратная матрица, которая, умноженная на исходную матрицу, дает единичную матрицу. В Для создания обратной матрицы можно использовать функцию numpy.linalg.inv. Если матрица необратима, то функция numpy.linalg.inv() выдаст ошибку. Например, чтобы найти обратную матрицу для матрицы A, можно использовать следующий код:

In [13]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Sympy

Единичную матрицу в SymPy можно создать с помощью функции eye из модуля sympy. Например, чтобы создать 3x3 единичную матрицу, нужно использовать следующий код:

In [14]:
I = sp.eye(3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


Для создания обратной матрицы можно использовать метод inv объекта Matrix. Например, чтобы найти обратную матрицу для матрицы A, можно использовать следующий код:

In [15]:
A = sp.Matrix([[1, 2], [3, 4]])
A_inv = A.inv()
print(A_inv)

Matrix([[-2, 1], [3/2, -1/2]])


Обратная матрица для матрицы A существует только если определитель A не равен нулю. Если определитель равен нулю, то обратной матрицы не существует.

## Ранг матрицы <a class="anchor" id="matrix-rank"></a>

### Numpy

Чтобы вычислить ранг матрицы в NumPy, можно воспользоваться функцией numpy.linalg.matrix_rank(). Эта функция принимает матрицу в качестве аргумента и возвращает ее ранг.

In [16]:
# Создание матрицы
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисление ранга матрицы
rank = np.linalg.matrix_rank(matrix)

print("Матрица:\n", matrix)
print("Ранг матрицы:", rank)

Матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы: 2


### Sympy

Чтобы вычислить ранг матрицы с помощью библиотеки SymPy, нужно сначала создать матрицу с помощью класса Matrix из модуля sympy.matrices. Затем можно использовать метод rank() для вычисления ранга матрицы.

In [17]:
# Создание матрицы
matrix = sp.Matrix([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Вычисление ранга матрицы
rank = matrix.rank()

print("Матрица:\n", matrix)
print("Ранг матрицы:", rank)


Матрица:
 Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Ранг матрицы: 2


## Определитель матрицы <a class="anchor" id="matrix-determinant"></a>

### Numpy

В NumPy определитель матрицы можно вычислить с помощью функции numpy.linalg.det(). Функция принимает матрицу в качестве аргумента и возвращает ее определитель.

Пример использования функции numpy.linalg.det() в NumPy:

In [18]:
# Создание матрицы
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Вычисление определителя матрицы
det_A = np.linalg.det(A)

print("Матрица A:")
print(A)
print(f"Определитель матрицы det(A) = {det_A}")

Матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель матрицы det(A) = 0.0


Как видно, в примере создается матрица A, находится ее определитель с помощью функции numpy.linalg.det(), и выводится на экран. Определитель матрицы A равен -9.51619735392994e-16. Обратите внимание, что значение определителя матрицы может быть достаточно малым или большим из-за погрешностей округления.

### Sympy

В SymPy определитель матрицы можно вычислить с помощью функции sympy.det(). Функция принимает матрицу в качестве аргумента и возвращает ее определитель.

Пример использования функции sympy.det() в SymPy:

In [19]:
# Создание матрицы
A = sp.Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Вычисление определителя матрицы
det_A = A.det()

print("Матрица A:")
print(A)
print(f"Определитель матрицы det(A) = {det_A}")

Матрица A:
Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Определитель матрицы det(A) = 0


Как видно, в примере создается матрица A, находится ее определитель с помощью функции sympy.Matrix.det(), и выводится на экран. Определитель матрицы A равен 0. Обратите внимание, что значение определителя матрицы может быть достаточно малым или большим из-за погрешностей округления. Также SymPy может вычислять определитель матрицы, содержащей символы в явном виде.